# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='titel',
            new_name='Title',
        ),
    ]
