# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 10:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20170110_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='StartTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 11, 10, 44, 12, 30105, tzinfo=utc)),
        ),
    ]
