# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20170111_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='End_Time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
