# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Title',
            field=models.CharField(max_length=240),
        ),
    ]
